version: '2'
services:
    tfgjhipsterapp-app:
        image: tfgjhipsterapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tfgjhipsterapp-mysql:3306/tfgjhipsterapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tfgjhipsterapp-elasticsearch:9300
        ports:
            - 8080:8080
    tfgjhipsterapp-mysql:
        extends:
            file: mysql.yml
            service: tfgjhipsterapp-mysql
    tfgjhipsterapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tfgjhipsterapp-elasticsearch
